# Generated by Django 5.1.3 on 2024-11-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Roommates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.CharField(max_length=100, verbose_name='Возраст')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('hobby', models.TextField(verbose_name='Хобби, кого ищете')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сожитель',
                'verbose_name_plural': 'Сожители',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=255, verbose_name='Название квартиры')),
                ('prace', models.CharField(max_length=50, verbose_name='Цена')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('description', models.TextField(default='Не указано', verbose_name='Описание квартиры')),
                ('parking', models.CharField(default='Не указано', max_length=150, verbose_name='Парковка')),
                ('contact', models.CharField(max_length=150, verbose_name='Контакты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie_app.category')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
