# Generated by Django 5.1.3 on 2024-11-28 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
