# Generated by Django 5.1.3 on 2024-11-30 13:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_app', '0003_rename_foto_roommates_imo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Найти комнату', 'Найти комнату'), ('Доля в комнате', 'Доля в комнате')], max_length=20)),
                ('location', models.CharField(choices=[('Алматы', 'Алматы'), ('Астана', 'Астана'), ('Караганда', 'Караганда')], max_length=50)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roommates_min', models.PositiveIntegerField(blank=True, null=True)),
                ('roommates_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=255, verbose_name='Название квартиры')),
                ('prace', models.CharField(max_length=50, verbose_name='Цена')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('description', models.TextField(default='Не указано', verbose_name='Описание квартиры')),
                ('parking', models.CharField(default='Не указано', max_length=150, verbose_name='Парковка')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('contact', models.CharField(max_length=150, verbose_name='Контакты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie_app.category')),
            ],
        ),
    ]
