# Generated by Django 5.1.3 on 2024-11-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_app', '0004_room_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
